import { NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { name, contact, message } = body

    if (!name || !contact || !message) {
      return NextResponse.json(
        { error: 'Required fields (Name, Contact info, and Message) are missing.' },
        { status: 400 }
      )
    }

    // 1. Save data to Supabase contact_messages table
    const { error: dbError } = await supabase
      .from('contact_messages')
      .insert([{
        name,
        contact,
        message
      }])

    if (dbError) {
      console.error('Supabase DB error:', dbError.message)
      return NextResponse.json(
        { error: `Database error: ${dbError.message}` },
        { status: 500 }
      )
    }

    // 2. Route Email to school admin using Resend
    if (process.env.RESEND_API_KEY) {
      const emailHtml = `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 12px; background-color: #fafafa;">
          <div style="background-color: #1E1E1E; padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 24px;">
            <h2 style="color: #F5B800; margin: 0; font-size: 22px;">New Contact Message</h2>
            <p style="color: #ffffff; margin: 5px 0 0 0; font-size: 14px;">Kinford School of Guidance</p>
          </div>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555; width: 180px;">Sender Name</td>
              <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Contact Info</td>
              <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;">${contact}</td>
            </tr>
          </table>
          <div style="margin-top: 24px;">
            <h4 style="color: #A0163B; margin-bottom: 8px;">Message:</h4>
            <div style="background-color: #ffffff; padding: 16px; border-radius: 8px; border: 1px solid #e2e8f0; font-style: italic; color: #333; white-space: pre-wrap;">
              ${message}
            </div>
          </div>
          <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #aaa;">
            This email was automatically generated by the Kinford Contact System.
          </div>
        </div>
      `;

      await resend.emails.send({
        from: 'Kinford School <noreply@kinfordschool.com>',
        to: 'kinfordschool@gmail.com',
        subject: `New Message from ${name}`,
        html: emailHtml,
      }).catch(err => {
        console.error('Error sending contact notification email:', err)
      })
    }

    return NextResponse.json({ success: true, message: 'Message sent successfully.' })
  } catch (err: any) {
    console.error('Server error inside contact handler:', err)
    return NextResponse.json(
      { error: err.message || 'An unexpected server error occurred.' },
      { status: 500 }
    )
  }
}
