import { NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'
import { Resend } from 'resend'

// Initialize Resend client using env key
const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { name, parent_name, email, phone, grade, gender, message, place, last_school_studied } = body

    // Validation
    if (!name || !email || !phone || !grade || !gender) {
      return NextResponse.json(
        { error: 'Required fields (Student Name, Parent Email, Phone, Grade, Gender) are missing.' },
        { status: 400 }
      )
    }

    // 1. Save data to Supabase enquiries table
    const { error: dbError } = await supabase
      .from('enquiries')
      .insert([{
        name,
        parent_name,
        email,
        phone,
        grade,
        gender,
        message,
        place,
        last_school_studied
      }])

    if (dbError) {
      console.error('Supabase DB error:', dbError.message)
      return NextResponse.json(
        { error: `Database error: ${dbError.message}` },
        { status: 500 }
      )
    }

    // 2. Check if RESEND_API_KEY is configured
    if (!process.env.RESEND_API_KEY) {
      console.warn('RESEND_API_KEY environment variable is not defined.')
      return NextResponse.json(
        { error: 'Email configuration is missing on the server.' },
        { status: 500 }
      )
    }

    // 3. Send Email 1: Notification to the School administration
    const schoolEmailHtml = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 12px; background-color: #fafafa;">
        <div style="background-color: #1E1E1E; padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 24px;">
          <h2 style="color: #F5B800; margin: 0; font-size: 22px;">New Admissions Enquiry</h2>
          <p style="color: #ffffff; margin: 5px 0 0 0; font-size: 14px;">Kinford School of Guidance</p>
        </div>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555; width: 180px;">Student Name</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Place</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;">${place || '—'}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Last School Studied</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;">${last_school_studied || '—'}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Parent Name</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;">${parent_name || '—'}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Email Address</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;"><a href="mailto:${email}">${email}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Phone Number</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;"><a href="tel:${phone}">${phone}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Gender</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;">${gender}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Grade Applying</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #111;"><span style="background-color: #F5B800; color: #1E1E1E; padding: 4px 10px; border-radius: 20px; font-size: 12px; font-weight: bold;">${grade}</span></td>
          </tr>
        </table>
        <div style="margin-top: 24px;">
          <h4 style="color: #A0163B; margin-bottom: 8px;">Message / Additional Info:</h4>
          <div style="background-color: #ffffff; padding: 16px; border-radius: 8px; border: 1px solid #e2e8f0; font-style: italic; color: #333; white-space: pre-wrap;">
            ${message || 'No additional message was provided.'}
          </div>
        </div>
        <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #aaa;">
          This email was automatically generated by the Kinford Admin System.
        </div>
      </div>
    `;

    const { error: schoolEmailError } = await resend.emails.send({
      from: 'Kinford School <noreply@kinfordschool.com>',
      to: 'kinfordschool@gmail.com',
      subject: `New Enquiry: ${name}`,
      html: schoolEmailHtml,
    })

    if (schoolEmailError) {
      console.error('Error sending email to school:', schoolEmailError)
    }

    // 4. Send Email 2: Confirmation receipt to the Parent
    const parentEmailHtml = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #eee; border-radius: 16px; background-color: #ffffff; box-shadow: 0 4px 12px rgba(0,0,0,0.05);">
        <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #f6f6f6; padding-bottom: 20px;">
          <h2 style="color: #A0163B; margin: 0; font-size: 24px; font-weight: bold; letter-spacing: -0.5px;">Kinford</h2>
          <p style="color: #F5B800; margin: 5px 0 0 0; font-size: 11px; text-transform: uppercase; letter-spacing: 2px; font-weight: 600;">School of Guidance</p>
        </div>
        <h3 style="color: #1E1E1E; font-size: 18px; margin-bottom: 16px;">Dear Parent / Guardian,</h3>
        <p style="color: #4a4a4a; font-size: 15px; line-height: 1.6; margin-bottom: 16px;">
          Thank you for your interest in Kinford School of Guidance. We have received your enquiry and will be in touch within 24 hours.
        </p>
        <p style="color: #4a4a4a; font-size: 15px; line-height: 1.6; margin-bottom: 24px;">
          At Kinford, we are dedicated to guiding students beyond academics, fostering structural assessment, creative oriented learning, and individual mentoring. We look forward to welcoming you and your child to the Kinford community.
        </p>
        <div style="background-color: #f8f6f2; border-left: 4px solid #A0163B; padding: 16px 20px; border-radius: 0 8px 8px 0; margin-bottom: 30px;">
          <span style="font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 4px;">Enquiry Summary</span>
          <strong style="color: #111; font-size: 14px; display: block;">Student: ${name} (${gender})</strong>
          <span style="color: #555; font-size: 14px; display: block;">Grade: ${grade}</span>
        </div>
        <p style="color: #1E1E1E; font-size: 15px; font-weight: 600; margin: 0 0 4px 0;">Warm regards,</p>
        <p style="color: #A0163B; font-size: 15px; font-weight: 700; margin: 0;">The Kinford Team</p>
        <div style="border-top: 1px solid #f0f0f0; margin-top: 36px; padding-top: 20px; text-align: center; font-size: 12px; color: #aaa;">
          Kinford School of Guidance • Thamarassery, Kozhikode, Kerala
        </div>
      </div>
    `;

    const { error: parentEmailError } = await resend.emails.send({
      from: 'Kinford School <noreply@kinfordschool.com>',
      to: email,
      subject: 'Your enquiry to Kinford has been received',
      html: parentEmailHtml,
    })

    if (parentEmailError) {
      console.error('Error sending confirmation email to parent:', parentEmailError)
    }

    return NextResponse.json({ success: true, message: 'Enquiry saved and emails routed successfully.' })
  } catch (err: any) {
    console.error('Server error inside enquiry handler:', err)
    return NextResponse.json(
      { error: err.message || 'An unexpected server error occurred.' },
      { status: 500 }
    )
  }
}

export async function DELETE(request: Request) {
  try {
    const { searchParams } = new URL(request.url)
    const id = searchParams.get('id')

    if (!id) {
      return NextResponse.json({ error: 'Missing enquiry ID parameter.' }, { status: 400 })
    }

    const { error } = await supabase
      .from('enquiries')
      .delete()
      .eq('id', id)

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, message: 'Enquiry deleted successfully.' })
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'An error occurred during deletion.' }, { status: 500 })
  }
}
