const { Client } = require('pg');

const connectionString = 'postgresql://postgres:%3FWGRkpAaKGX3cyk@db.ecazlhecquqtrkcrvejw.supabase.co:5432/postgres';

async function main() {
  console.log('Connecting to database...');
  const client = new Client({
    connectionString,
    ssl: {
      rejectUnauthorized: false
    }
  });

  try {
    await client.connect();
    console.log('Connected successfully. Creating table enquiries...');
    
    const query = `
      CREATE TABLE IF NOT EXISTS enquiries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        parent_name TEXT,
        phone TEXT NOT NULL,
        grade TEXT NOT NULL,
        message TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `;
    
    await client.query(query);
    console.log('Table enquiries created successfully (or already exists).');
  } catch (err) {
    console.error('Error executing migration:', err);
    process.exit(1);
  } finally {
    await client.end();
  }
}

main();
